services:
  satisfactory-server:
    image: 'satisfactory-arm-server'
    container_name: 'satisfactory-arm-server'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
      - '8888:8888/tcp'
    restart: 'unless-stopped'
    volumes:
      - './docker-compose.yml:/run/host-owner:ro'
      - './server_save_file:/home/satisfactory/.config/Epic'
      - './server_file:/home/satisfactory/server-file'
